version: '3.8'

name: manvsim

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: prod
    ports:
      - "5002:5002"
    volumes:
      - manvsim-db:/usr/src/app/server/instance
      - manvsim-db:/usr/src/app/server/media/instance


  app:
    build:
      context: app
      dockerfile: Dockerfile
      target: serve-prod
    ports:
      - "5001:5001"
    depends_on:
      - server


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/component_mapping.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - app

volumes:
  manvsim-db: