version: '3.8'

name: manvsim

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: t3zgVzcWTd3WV8KTmnNH
    volumes:
      - ./config/postgres/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"


  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: prod
    env_file:
      - server/.env
    ports:
      - "5002:5002"
    volumes:
      - ./certs/fullchain.pem:/usr/src/app/server/fullchain.pem
      - ./certs/privkey.pem:/usr/src/app/server/privkey.pem


  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: serve-prod
    ports:
      - "5001:5001"
    volumes:
      - ./certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./certs/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - server


  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: serve-prod
    ports:
      - "50003:50003"
    volumes:
      - ./certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./certs/privkey.pem:/etc/nginx/ssl/privkey.pem


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/component_mapping.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - app

volumes:
  manvsim-db: