version: '3.8'

name: manvsim

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
        - config/postgres/.env
    volumes:
      - manvsim-db:/var/lib/postgresql/data
      - ./config/postgres/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"


  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: prod
    env_file:
      - config/server/.env
      - config/postgres/.env
    ports:
      - "5002:5002"
    volumes:
      - manvsim-media:/usr/src/app/server/media/instance
      - ./config/certs/fullchain.pem:/usr/src/app/server/fullchain.pem
      - ./config/certs/privkey.pem:/usr/src/app/server/privkey.pem


  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      target: serve-prod
    ports:
      - "5001:5001"
    volumes:
      - ./config/certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./config/certs/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - server


  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: serve-prod
    ports:
      - "50003:50003"
    volumes:
      - ./config/certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./config/certs/privkey.pem:/etc/nginx/ssl/privkey.pem


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/component_mapping.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - app

volumes:
  manvsim-db:
  manvsim-media: