openapi: 3.0.1

info:
  title: MANVSim Media API
  description: Specification of the MANVSim servers' media API, that provides access to standard and user-uploaded static media files.
  version: 0.1.0

paths:

  /media/static/{filename}:
    get:
      summary: Get predefined static media files
      description: This endpoint retrieves **predefined** media files.
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Image in format `{.png, .jpg, .jpeg, .gif, .webp}`, video in format `{.mp4, .mov", .mkv}`, audio in format `{.mp3, .wav, .ogg, .flac}`, text in format `{.txt}`
        '404':
          description: File not found.


  /media/instance/{filename}:
    get:
      summary: Get user-uploaded static media files
      description: This endpoint retrieves **user-uploaded** media files.
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Image in format `{.png, .jpg, .jpeg, .gif, .webp}`, video in format `{.mp4, .mov", .mkv}`, audio in format `{.mp3, .wav, .ogg, .flac}`, text in format `{.txt}`
        '404':
          description: File not found.
  

  /media/{filename}:
    post:
      summary: Allows users to upload media files to the server
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
          description: The name of the file being uploaded. 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Allowed are images in format `{.png, .jpg, .jpeg, .gif, .webp}`, videos in format `{.mp4, .mov", .mkv}`, audio in format `{.mp3, .wav, .ogg, .flac}`, text in format `{.txt}`
      responses:
        '201':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaData'
        '400':
          description: No file part in request or No file provided
        '403':
          description: Forbidden file format


  /media/txt:
    post:
      summary: Returns a valid MediaData-JSON for raw text
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Optional title for text content
                text:
                  type: string
                  description: Raw text content
      responses:
        '201':
          description: MediaData-JSON created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaData'

        '400':
          description: No 'title' or 'text' field submitted


components:

  schemas:

    MediaData:
      type: object
      properties:
        media_type:
          type: string
        title:
          type: string
        text:
          type: string
        media_reference:
          type: string
      required: [ media_type ]