"""empty message

Revision ID: 06903a4c678d
Revises: 53a3f9ceba2d
Create Date: 2024-06-17 15:15:42.979695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06903a4c678d'
down_revision = '53a3f9ceba2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_web_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_user')
    # ### end Alembic commands ###
