"""empty message

Revision ID: 300effd77af4
Revises: 95e4c94bb176
Create Date: 2024-07-02 11:36:33.424897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '300effd77af4'
down_revision = '95e4c94bb176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('injuries')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('injuries', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
