"""empty message

Revision ID: 8798f89be63d
Revises: dfcb32280ee3
Create Date: 2024-08-13 11:13:15.611309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8798f89be63d'
down_revision = 'dfcb32280ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takes_part_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takes_part_in', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
