"""empty message

Revision ID: 95e4c94bb176
Revises: 985b081ce4e4
Create Date: 2024-07-02 11:33:27.232957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '95e4c94bb176'
down_revision = '985b081ce4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('results',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumable', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('consumable')

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('results',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
