"""empty message

Revision ID: dfcb32280ee3
Revises: e25eeba89926
Create Date: 2024-08-13 11:03:22.253305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcb32280ee3'
down_revision = 'e25eeba89926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_quantity_in_scenario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_location_quantity_in_scenario_location_id_location')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_location_quantity_in_scenario_scenario_id_scenario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_quantity_in_scenario'))
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vehicle', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('is_vehicle')

    op.drop_table('location_quantity_in_scenario')
    # ### end Alembic commands ###
