"""empty message

Revision ID: ed494d5ea048
Revises: 2aaa2c1e5ed6
Create Date: 2024-07-01 18:36:50.251232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed494d5ea048'
down_revision = '2aaa2c1e5ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_event', schema=None) as batch_op:
        batch_op.alter_column('execution',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_event', schema=None) as batch_op:
        batch_op.alter_column('execution',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
