"""empty message

Revision ID: ef3b5e9322e5
Revises: b9b45e484246
Create Date: 2024-06-17 12:48:48.897449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3b5e9322e5'
down_revision = 'b9b45e484246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
