name: Android Build

on:
 push:
  paths: 
   - 'app/**'
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Clone repository
     uses: actions/checkout@v4
   - name: Set up Java
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'zulu'
   - name: Set up Flutter
     uses: subosito/flutter-action@v2
     with:
       flutter-version: '3.24.1'
       channel: stable
   - name: pub get
     working-directory: app
     run: flutter pub get
     
   - working-directory: app
     run: flutter build apk
    
   - working-directory: app 
     run: flutter build appbundle
     
