name: Server Lint & Code Quality & Test
on:
  push:
    branches:
      - main
      - feature/server/**
      - feature/chore/**
      - feature/web/**
      - bug/server/**

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      working-directory: ${{ steps.set-working-directory.outputs.working-directory }}
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install pipenv
        working-directory: server
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        working-directory: server
        run: |
          pipenv install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    working-directory: server
    steps:
      - name: Run linter
        run: |
          pipenv run lint

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    working-directory: server
    steps:
      - name: Run Type Checker
        run: |
          pipenv run typecheck

  test:
    needs: setup
    runs-on: ubuntu-latest
    working-directory: server
    steps:
      - name: Run pytest
        run: |
          pipenv run pytest