name: Server Lint & Code Quality & Test
on:
  push:
    branches:
      - main
      - feature/server/**
      - feature/chore/**
      - feature/web/**
      - bug/server/**

jobs:
  
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pipenv
        working-directory: server
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        working-directory: server
        run: |
          pipenv install

      - name: Run linter
        working-directory: server
        run: |
          pipenv run lint

      - name: Run Type Checker
        working-directory: server
        run: |
          pipenv run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pipenv
        working-directory: server
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        working-directory: server
        run: |
          pipenv install

      - name: Run pytest
        working-directory: server
        run: |
          pipenv run pytest
