name: Server Lint & Code Quality & Test
on:
  push:
    branches:
      - main
      - feature/server/**
      - feature/chore/**
      - feature/web/**
      - bug/server/**

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install pipenv
        working-directory: server
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        working-directory: server
        run: |
          pipenv install

      - name: Run linter
        working-directory: server
        run: |
          pipenv run lint

      - name: Run Type Checker
        working-directory: server
        run: |
          pipenv run typecheck

      - name: Initialize database
        working-directory: server
        run: |
          pipenv run flask --app main db init 2>/dev/null | true
          pipenv run flask --app main db upgrade

      - name: Load test data to database
        working-directory: server
        run: |
          pipenv run python dbsetup.py

      # Test server component
      - name: Run pytest
        working-directory: server
        run: |
          pipenv run pytest
